spring:
  datasource:
    data1:
      jdbc-url: jdbc:mysql://172.20.53.197:3306/microservice?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: Ufsoft*123
      driver-class-name: com.mysql.cj.jdbc.Driver
#    test2:
#      url: jdbc:mysql://172.20.53.197:3306/microservice?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: Ufsoft*123
#      driver-class-name: com.mysql.cj.jdbc.Driver